### ISSUE TITLE
[Question] Is it impossible to keep adding data while getting summary for quantiles?

### ISSUE THREAD

**Issue by etsangsplk** [axiomhq/quantiles#3]
I am researching what online data structure that can help answering the questions like
: top X events so far
: top X event by this key so far
: top 10% of events so far ..
But otice that it is required to call Finalize() before getting any summary results. 
And I cannot push any more events post Finalize().
Is each instance of Sketch only for one off computation? And need  to be thrown away and use a new instance of Sketch for a new question?

I have similar questions about hyperlolog repo and flipcounter

**Comment by seiflotfy** [comment]
Create a new Sketch then use PushSummary() which pushes full summary while maintaining approximation error invariants.
https://github.com/axiomhq/quantiles/blob/master/sketch.go#L101
